### ISSUE TITLE
launch-pangeo-on-cheyenne script host name issue

### ISSUE THREAD

**Issue by vprzybylo** [NCAR/pangeo#3]
In the launch-pangeo-on-cheyenne script, it is not capturing the host name correctly (the port # is fine).  In the tunnel command to ssh in:

cmd="ssh -N -L localhost:${LOCALPORT}:{REMOTE HOST}:${PORT} ${REM_USER}@cheyenne.ucar.edu"

it is not able to connect to http://localhost:8888/ without hardcoding the correct host name, opening a new terminal, and correctly 'ssh'ing in.  There was a suggestion to have a unique log file each time you run from @mnlevy1981

**Comment by ksulia** [comment]
I have installed and activated the pangeo-cheyenne environment, and have the pangeo environment set on my account on Cheyenne.
When attempting to establish a connection using the script, the follow occurs:

./launch-pangeo-on-cheyenne -u sulia -A UALB0018 -e pangeo -w 12:00:00
Token_Response:
Thu Nov 29 11:29:58 MST 2018
waiting for job to run............................................................
still waiting............................................................
still waiting............................
Thu Nov 29 11:32:28 MST 2018
It's taking too long to launch jupyter lab, aborting!
Here's what was in the jupyter lab log:
hostname = r8i1n26
/var/spool/pbs/mom_priv/jobs/3523426.chadmin1.SC: line 16: jupyter: command not found


I have also launched jupiter lab successfully on my account on cheyenne, both in /glade/u/home/sulia and /glade/work/sulia directories, and within the pangeo environment.  Any thoughts on why jupiter cannot be found?

**Comment by mnlevy1981** [comment]
@ksulia When you launch jupyter on cheyenne, what conda environment are you using? The `-e pangeo` argument to `launch-pangeo-on-cheyenne` tells the script to use the `pangeo` environment in conda, but if you relied on `server-side/pangeo-cheyenne.yaml` then your environment on cheyenne will be named `pangeo-cheyenne` (which is the default for the `-e` argument)

**Comment by mnlevy1981** [comment]
@ksulia Looking further, it seems like conda is not being added to your path when using the script:

```
$ cat ~sulia/pangeo.o3523426
/var/spool/pbs/mom_priv/jobs/3523426.chadmin1.SC: line 11: activate: No such file or directory
/var/spool/pbs/mom_priv/jobs/3523426.chadmin1.SC: line 16: jupyter: command not found
```

One possibility is that this comes from your `.bashrc` script, which starts with

```
$ head -n 5 ~sulia/.bashrc
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

and ends with

```
$ tail -n 2 ~sulia/.bashrc
# added by Miniconda3 installer
export PATH="/glade/u/home/sulia/miniconda3/bin:$PATH"
```

Perhaps when ssh-ing to launch jupyter, `.bashrc` is exiting before adding conda to your path? If that's the case, moving the last two lines of the file to the top (ahead of the `case` command) should do the trick.

**Comment by ksulia** [comment]
@mnlevy1981 Thank you for the response and advice!  To answer your first question, yes I have the environment in the script set to 'pangeo' as that matches the environment on Cheyenne.

Your second suggestion on the .bashrc file seemed to have fixed the "jupyter not found" issue!  Unfortunately, I am still getting kicked off and am never able to connect:

./launch-pangeo-on-cheyenne -u sulia -A UALB0018 -e pangeo -w 12:00:00
Token_Response:
Thu Nov 29 13:19:40 MST 2018
waiting for job to run............................................................
Thu Nov 29 13:20:40 MST 2018
It's taking too long to launch jupyter lab, aborting!
Here's what was in the jupyter lab log:
hostname = r6i1n8
[W 13:20:47.413 LabApp] JupyterLab server extension not enabled, manually loading...
[I 13:20:47.430 LabApp] JupyterLab extension loaded from /glade/u/home/sulia/miniconda3/envs/pangeo/lib/python3.6/site-packages/jupyterlab
[I 13:20:47.430 LabApp] JupyterLab application directory is /gpfs/u/home/sulia/miniconda3/envs/pangeo/share/jupyter/lab
[I 13:20:47.432 LabApp] Serving notebooks from local directory: /gpfs/u/home/sulia/IPAS_Aug2018/IPAS_array
[I 13:20:47.432 LabApp] The Jupyter Notebook is running at:
[I 13:20:47.432 LabApp] http://r6i1n8:8888/
[I 13:20:47.432 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Perhaps I am pointing to the incorrect path?  I have tried quite a few and none seem to work.

Thank you!

**Comment by mnlevy1981** [comment]
@ksulia It looks like your jupyter configuration is a little different than mine -- where you see

```
[I 13:20:47.432 LabApp] The Jupyter Notebook is running at:
[I 13:20:47.432 LabApp] http://r6i1n8:8888/
```

I see

```
[I 17:43:12.481 LabApp] The Jupyter Notebook is running at:
[I 17:43:12.481 LabApp] http://r6i6n30:8888/?token=914a1cb112e7c9e1aa1d2c80c3406664d160e9fae20d2ed9
```

And the `launch-pangeo-on-cheyenne` is specifically looking for the word `token` in the URL to parse everything out. Unfortunately I'm not familiar with how jupyter can be configured -- I think the problem might be something in `/glade/u/home/sulia/.jupyter/jupyter_notebook_config.json` but I do not have read permissions for that file so I can't say for sure. I looked through the [Jupyter security page](https://jupyter-notebook.readthedocs.io/en/stable/security.html) but didn't see anything that might indicate why you aren't being given a token.

As an aside, you probably have a job running on cheyenne that you can log in and kill (unfortunately I don't see the jobid in the output above so you'll need to run `qstat` to find it).

**Comment by ksulia** [comment]
@mnlevy1981 interesting..

So my /glade/u/home/sulia/.jupyter/jupyter_notebook_config.json contains a password under "NotebookApp", which looks somewhat similar to a token. When I launch jupyter lab from command line no password or token is generated and I am automatically logged in, so I image this password is being forwarded to the browser, at least that would be my guess!

So I wonder if I should some how turn off the automatic password so that I can receive a token.

I am continually troubleshooting logging in with the ./launch script, and I have been in the "still waiting..." phase, so that is probably the job you are seeing.

Thanks again for your help!

**Comment by mnlevy1981** [comment]
I think if you remove the NotebookApp password then you'll have a token generated, and then the launch script should work (or at least get a little further before throwing a different error)

**Comment by ksulia** [comment]
Unfortunately, that seemed to make things worse. Now I am unable to launch jupyter when logged into Cheyenne as well as via the launch script, with the same error (beginning snippet of error below). 


./launch-pangeo-on-cheyenne -u sulia -A UALB0018 -e pangeo -w 12:00:00
Token_Response:
Fri Nov 30 09:18:10 MST 2018
waiting for job to run............................................
Fri Nov 30 09:18:54 MST 2018
It's taking too long to launch jupyter lab, aborting!
Here's what was in the jupyter lab log:
hostname = r6i3n3
[E 09:18:58.589 LabApp] Exception while loading config file /gpfs/u/home/sulia/.jupyter/jupyter_notebook_config.json
    Traceback (most recent call last):
      File "/glade/u/home/sulia/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/glade/u/home/sulia/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/config/loader.py", line 406, in load_config
        dct = self._read_file_as_dict()
      File "/glade/u/home/sulia/miniconda3/envs/pangeo/lib/python3.6/site-packages/traitlets/config/loader.py", line 412, in _read_file_as_dict
        return json.load(f)

**Comment by mnlevy1981** [comment]
Hmm, that looks like there's an issue in the formatting of the JSON file. My config file looks like

```
{
  "NotebookApp": {
    "nbserver_extensions": {
      "nbserverproxy": true
    }
  }
}
```

Do you have some extraneous `{` or `}` after removing the password?

**Comment by ksulia** [comment]
That was the key!!  

So, I followed the instructions here: https://pangeo.readthedocs.io/en/latest/setup_guides/hpc.html to create the pangeo environment, and when I followed the steps to create the jupyter notebook password, it automatically populated my config file with the password as I mentioned.  The piece that you just sent was never in the config file.  I replaced my config file with what appears in yours, and now a token is generated when i log in locally and through the tunnel.

I wonder if there were some steps I missed in order to add that piece to the config file, or if I was not supposed to generate a password as that website suggested?

Anyway, it appears everything is working.  Thank you so much for your help!!

**Comment by mnlevy1981** [comment]
It seems like the issue comes down to inconsistencies between the instructions in https://pangeo.readthedocs.io/en/latest/setup_guides/hpc.html and the instructions in https://github.com/NCAR/pangeo/blob/master/server-side/README.md -- I should probably update the latter to be in line with the official pangeo recommendations (and then update the launch script accordingly).

Sorry this tripped you up, but I'm glad it's finally working! I'll try to find some time to fix it, and let me know if you run into any more issues.

**Comment by ksulia** [comment]
I see, and no worries! -- I would have never known what the config file should contain if I had not ran into this issue, so now next time I will know what to look for. I really appreciate your help.
